name: device_integrity_plugin
description: >
  Flutter plugin for separate Android and iOS device integrity signals, with
  Play Integrity and App Attest support.
version: 0.1.0
homepage: https://github.com/sanuponnulli/device_integrity_plugin
repository: https://github.com/sanuponnulli/device_integrity_plugin
issue_tracker: https://github.com/sanuponnulli/device_integrity_plugin/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.sanuponnulli.device_integrity_plugin
        pluginClass: DeviceIntegrityPlugin
      ios:
        pluginClass: DeviceIntegrityPlugin
